### ISSUE TITLE
Source-word dropout as corruption

### ISSUE THREAD

**Issue by wangwang110** [grammatical/neural-naacl2018#6]
where is the corresponding code in marian or preprocessing?

**Comment by snukky** [comment]
This is just dropout over source embeddings. The corresponding code pieces in Marian:
https://github.com/marian-nmt/marian-dev/blob/master/src/models/transformer.h#L566
https://github.com/marian-nmt/marian-dev/blob/master/src/graph/expression_operators.h#L213

**Comment by wangwang110** [comment]
> This is just dropout over source embeddings. The corresponding code pieces in Marian:
> https://github.com/marian-nmt/marian-dev/blob/master/src/models/transformer.h#L566
> https://github.com/marian-nmt/marian-dev/blob/master/src/graph/expression_operators.h#L213

"To make the task harder, we add dropout over source words, setting the full embedding vector for a source word to 1/psrc with a probability of psrc. During our experiments, we found psrc = 0.2 to work best "
is it means that set the embedidngs of 20% words to [5,5,5]  (if the embedding_size =3) ?

**Comment by snukky** [comment]
We've discussed this and agreed that this is a really bad explanation and that there was an error, it should be:
> To make the task harder, we add dropout over  source words, setting the full embedding vector for a source word to $0$ with a probability $p_{\textrm{src}}$, all other embedding values are scaled with $1/(1-p_{\textrm{src}})$. During our experiments, we found $p_{\textrm{src}}=0.2$ to work best.

We'll update this in published versions of the paper. Implementation in Marian is correct.

Thanks!
