### ISSUE TITLE
BPE model

### ISSUE THREAD

**Issue by weiqi94** [grammatical/neural-naacl2018#8]
Hi,
I want to re-train the bpe model. So I wonder which dataset you used for training the bpe model and if you only use the source part, target part or both. Besides, what is the parameter you used, i.e.,  bpe_operations. Thanks!

**Comment by snukky** [comment]
I don't remember which data we have used exactly, but it was the target side of NUCLE and Lang-8, and maybe some monolingual data. Originally we have 50k subword pieces.

Currently I use 32k subword units trained solely on monolingual data with SentencePiece and this also works fine.

**Comment by snukky** [comment]
Feel free to reopen if you have more questions in this topic.
